### ISSUE TITLE
IPEDS fall enrollment age files

### ISSUE THREAD

**Issue by mchingos** [UrbanInstitute/education-data-package-stata#37]
"college ipeds fall-enrollment age sex" does not produce sex breakdowns by default, and I think it should.

Also, the default in both the age and age sex files appears to be to include breakdowns by level_of_study but only totals by ftpt. Should we be consistent about this, and have the default to be breakdowns by both or neither? And make whatever the default is clear in the documentation?

Also, degree_seeking breakdowns only appear to be available in 1991 and 1993. @ericatheresa can we mention this in the documentation?

**Comment by mchingos** [comment]
And asking for breakdowns by sex and FTPT does not appear to work for some reason:

. educationdata using "college ipeds fall-enrollment age sex", sub("ftpt=1,2 sex=1,2 year=2015") clea
> r
Please be patient - Downloading data from API. I'll give you a time estimate shortly.
 Error -675, Unable to open URL: server reported server error
          getalltables():  3010  attempt to dereference NULL pointer
            getalldata():     -  function returned error
                 <istmt>:     -  function returned error

**Comment by grahamimac** [comment]
As to the first question, I leave that to @ericatheresa.

For the second question, I'm going to start an issue in the main repository, as it looks like these filters should work but produce a 500 error. We're currently hunting for all of these, so thanks for finding one!

**Comment by mchingos** [comment]
Also getting it on class_level: 
. educationdata using "college ipeds fall-enrollment race", sub(unitid=100654 year=2015 class_level=1
> :99) clear
Please be patient - Downloading data from API. I'll give you a time estimate shortly.
 Error -675, Unable to open URL: server reported server error
          getalltables():  3010  attempt to dereference NULL pointer
            getalldata():     -  function returned error
                 <istmt>:     -  function returned error
r(3010);

. educationdata using "college ipeds fall-enrollment race", sub(unitid=100654 year=2015 class_level=1
> ,2,3,4,99) clear
Please be patient - Downloading data from API. I'll give you a time estimate shortly.
 Error -675, Unable to open URL: server reported server error
          getalltables():  3010  attempt to dereference NULL pointer
            getalldata():     -  function returned error
                 <istmt>:     -  function returned error

**Comment by grahamimac** [comment]
This is no longer producing an error, but it does not filter as it should. I've added this as an issue for Dave in the API.

**Comment by grahamimac** [comment]
This is now resolved per the link above my previous comment by Dave. If you have any other issues like this, please let us know! Closing.
