### ISSUE TITLE
Broken filter

### ISSUE THREAD

**Issue by mchingos** [UrbanInstitute/education-data-package-stata#40]
Filtering on unitid does not work for "college ipeds outcome-measures"

**Comment by grahamimac** [comment]
Hi Matt, you're correct, that should work, and seems to just be returning the full dataset. I've added it to the same issue in the main repository for the API for Dave to inspect and linked back here.

**Comment by ddorio** [comment]
@grahamimac and @mchingos - This is fixed. Checked at https://educationdata-stg.urban.org/api/v1/college-university/ipeds/outcome-measures/2015/?unitid=100654&r=1
(I added the r=1 so I didn't get a cached version)

**Comment by grahamimac** [comment]
Confirmed on the Stata end. Thanks for the find Matt and the quick fix Dave!
