### ISSUE TITLE
Add wildcard?

### ISSUE THREAD

**Issue by mchingos** [UrbanInstitute/education-data-package-stata#41]
Would it be easy to add a wildcard for the sub() option, so that e.g. if you want to get breakdowns by all values of ftpt you'd just write sub(ftpt=*) rather than looking up all possible values of ftpt and then writing sub(ftpt=1,2,99)?

**Comment by grahamimac** [comment]
Thanks Matt. I think the point of the filter is to do this wildcard-ing by default. Is there an example you can provide where this isn't happening, so I can take a look?

**Comment by mchingos** [comment]
It appears that the default behavior has changed since I posted this issue, so I think you can close it.

**Comment by grahamimac** [comment]
I was hoping that was the case. Closing as this is now resolved. Thanks Matt!
