### ISSUE TITLE
Degree-seeking label

### ISSUE THREAD

**Issue by ericatheresa** [UrbanInstitute/education-data-package-stata#43]
Strangely the degree_seeking label for 99 ("Total") doesn't seem to be populated (although it's in the api_values csv). Any idea why? @grahamimac @ddorio

**Comment by grahamimac** [comment]
@ericatheresa Finally getting around to closing out these issues. Do you recall the command you ran so I can replicate and fix?

**Comment by ericatheresa** [comment]
educationdata using "college ipeds fall-enrollment race sex", sub(year=2014) clear

Feel free to kill it after it hits one page, it doesn't need to load all the data.

**Comment by grahamimac** [comment]
Hi Erica - I looked into it, and in the call https://educationdata.urban.org/api/v1/api-endpoint-varlist/?endpoint_id=13, it looks like the format_name for "degree_seeking" is "yes_no", which just labels the 0 and 1 values, and does not have a label for 99. It looks like the format_name should be "degree_seeking", which has the correct label for 0, 1 and 99. 

@ericatheresa @ddorio I'm not sure which one of you can change this, but once this is changed on the API, this issue will be resolved.

**Comment by ericatheresa** [comment]
Ah coulda sworn I checked this as that was my suspicion as well. Thanks! @ddorio should I just output that one row? if so, do you use the api_variables or api_variable_list (two rows) for this info? (we have the format variable in both)

**Comment by ddorio** [comment]
@ericatheresa @grahamimac 

I changed the format on the api_variables or api_variable_list for degree_seeking to 'degree_seeking'.  Viewed on https://educationdata.urban.org/api/v1/api-endpoint-varlist/?endpoint_id=13. 

Closing this issue....
