### ISSUE TITLE
suggestion based on user feedback

### ISSUE THREAD

**Issue by mchingos** [UrbanInstitute/education-data-package-stata#44]
When time estimate is very long (i.e. above some threshold we define), package could display a message along the lines of "consider downloading flat files from educationdata.urban.org"

**Comment by grahamimac** [comment]
Hi Matt,

Yes this is something I've been thinking about, and the next step here is to allow users to select the ability to download from CSV, if they'd like (e.g., for long file downloads, as you point out). I'm going to add a point to the conversation on the API Issues, as right now there is a field title CSV location that is null that would make my life much easier were it filled in with the location of the CSV URL. I'll keep you updated.

**Comment by ddorio** [comment]
@grahamimac That field can't be used because there are multiple files associated with a single endpoint. If you go to https://educationdata-stg.urban.org/api/v1/api-downloads/ you can use the endpoint ID to get the associated downloads.

**Comment by grahamimac** [comment]
Saw that when I went to the website and edited my comment, probably right when you posted yours, thanks Dave!

**Comment by grahamimac** [comment]
Ability to download from CSV is now implemented in the 0.2 release, which is coming soon. Closing now.
