### ISSUE TITLE
csv errors

### ISSUE THREAD

**Issue by mchingos** [UrbanInstitute/education-data-package-stata#46]
The csv option works for me in Stata 14, but not in Stata 15, which gives the following error:

. educationdata using "college ipeds directory", csv
Please be patient - downloading data.
Downloading file, please wait...
unable to open temp_eddata_file_gen_012345.csv for writing
                 stata():  3598  Stata returned error
               copycsv():     -  function returned error
           downloadcsv():     -  function returned error
            getalldata():     -  function returned error
                 <istmt>:     -  function returned error

**Comment by mchingos** [comment]
Also, this command ran in Stata 14 but produced no records even though I think it should have:
educationdata using "school ccd enrollment race", sub(year=2013 grade=99) csv clear

**Comment by grahamimac** [comment]
Hi Matt - thanks for the issue. I ran into the same issue testing this morning and it's a result of Stata15 setting the default working directory where it's installed, while Stata14 defaults to your home directory on the D drive. 

In the next release, I've added language telling people to change their working directory using the "cd" command, in the program and in the documentation. Once you do that, you should be fine.

**Comment by grahamimac** [comment]
I am currently looking into the second issue (it takes a long time to download, load, and test...)

**Comment by mchingos** [comment]
Thanks. Glad it’s an easy fix. Another thought: maybe add some text after after time estimate (if csv option not specified) along the lines of “if data is taking too long to download, consider using csv option”

Sent from my iPhone

On Jun 26, 2018, at 9:39 AM, Graham MacDonald <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Matt - thanks for the issue. I ran into the same issue testing this morning and it's a result of Stata15 setting the default working directory where it's installed, while Stata14 defaults to your home directory on the D drive.

In the next release, I've added language telling people to change their working directory using the "cd" command, in the program and in the documentation. Once you do that, you should be fine.

**Comment by grahamimac** [comment]
A step ahead of you. This language is already in the release 0.2.0 that you have (it's a lot of text, so you may have missed it). 

```
If this time is too long for you to wait, try adding the "csv" option to the end of your command to download the full csv directly.
```

**Comment by grahamimac** [comment]
Ok, I found the problem with grade (it was only with grade) and resolved it in the next release.
