### ISSUE TITLE
Syntax for year range

### ISSUE THREAD

**Issue by mchingos** [UrbanInstitute/education-data-package-stata#48]
Can we use year ranges in more of the examples in the help file (i.e. year=2010:2013 rather than just year=2011)? One user got frustrated using the package because it wasn't obvious how to pull multiple years of data, and the biggest benefit of what we've done is helping people pull multiple years of data easily.

**Comment by grahamimac** [comment]
Easy fix, I'll add this to my to do list and get you a version for your feedback soon.

**Comment by grahamimac** [comment]
Resolved by latest release, closing.
