### ISSUE TITLE
error r(3499)

### ISSUE THREAD

**Issue by RichMurphy** [UrbanInstitute/education-data-package-stata#49]
Hi, 
First time user, so could be user error. 
I'm using Stata 15.1, installed educationdata, libjson and ran adoupdate. 
When trying any of thesimple examples for obtaining the data keep getting the same error- r(3499);

educationdata using "college ipeds directory"
            getalldata():  3499  endpointstrings() not found
                 <istmt>:     -  function returned error
r(3499);

Suggestions?

**Comment by grahamimac** [comment]
Hi @RichMurphy , 

Thanks for your comment and error report!

I don't think it's user error, but it could be related to the order of installations. It seems as if Stata has read in one of the functions in the underlying package but not another, even though they're in the same script. I just tried to replicate the error in 15.1 using the same process you describe and everything works fine.

As I am in our TECH department, I'm going to ask you to uninstall and re-install the package, then try again, and report what you see:

```
ado uninstall educationdata
net install educationdata, replace from("https://urbaninstitute.github.io/education-data-package-stata/")
```

Then rerun your command above. P.S. if you really want all that data, however, I recommend using the csv option, which will be faster. See the documentation for more info: 

```
educationdata using "college ipeds directory", clear csv
```

I hope that helps. Please let me know if it doesn't resolve and we can dig further.

**Comment by RichMurphy** [comment]
Hi, 
That worked perfectly.  "Data successfully loaded into Stata and ready to use."
I think you were right about the order of installation. 
At first I had only installed 'educationdata', which lead to a very long series of errors when trying to download files. 
So I then I ran adoupdate, which then got me to the r(3499) error.
Seems like users need to ensure adoupdate is run first. 

Thanks
Rich

**Comment by adamrossnelson** [comment]
Giving this a bump. I experienced the same error. And the solution described above fixed the glitch.

Might be worth giving this a mention on the repo's ReadMe.md.

Also, thanks to UI for the work on this. Great work. So glad to have this.
