### ISSUE TITLE
error message from Stata command

### ISSUE THREAD

**Issue by mchingos** [UrbanInstitute/education-data-package-stata#50]
. educationdata using "school ccd enrollment race sex", sub(year=2014 grade=4 race=3 sex=2)
Please be patient - downloading data.

I estimate that the download for the entire file you requested will take between 2 minute(s) and 16 minute(s).
This is only an estimate, so actual time may vary due to internet speed and file size differences.

Progress for each endpoint and call to the API will print to your screen. Please wait...
If this time is too long for you to wait, try adding the "csv" option to the end of your command to download the 
> full csv directly.

Getting data from /api/v1/schools/ccd/enrollment/2014/grade-4/race/sex/?race=3&sex=2, endpoint 1 of 1 (100187 rec
> ords).
Endpoint 1 of 1: On page 2 of 101
 Error -679, Unable to open URL: unexpected web error
              gettable():  3010  attempt to dereference NULL pointer
          getalltables():     -  function returned error
            getalldata():     -  function returned error
                 <istmt>:     -  function returned error
r(3010);

**Comment by mchingos** [comment]
Now I get this error:

. educationdata using "school ccd enrollment race sex", sub(year=2014 grade=4 race=3 sex=2)
Please be patient - downloading data.
 Error -679, Unable to open URL: unexpected web error
          getalltables():  3010  attempt to dereference NULL pointer
            getalldata():     -  function returned error
                 <istmt>:     -  function returned error

**Comment by ddorio** [comment]
@mchingos can you run that again?

**Comment by mchingos** [comment]
yes, works now -- thanks!

**Comment by ddorio** [comment]
Yay! Thanks!
