### ISSUE TITLE
Error messages reported by user

### ISSUE THREAD

**Issue by mchingos** [UrbanInstitute/education-data-package-stata#51]
From user: I love the idea of the tool, but having some difficulty getting it to work (see error output below).  I’m working on Stata 14MP on a Mac Pro - I’m mainly relaying for your information, but if you have suggestions for me to try I’d be grateful.

. educationdata using "college ipeds fall-enrollment age sex"
type mismatch:  pointer = real not allowed type mismatch:  -> (pointing to):  transmorphic found where pointer expected 'return' found where almost anything else expected expression invalid class libjson undefined
                 <istmt>:  3499  numrows not found type mismatch:  -> (pointing to):  transmorphic found where pointer expected type mismatch:  -> (pointing to):  transmorphic found where pointer expected type mismatch:  -> (pointing to):  transmorphic found where pointer expected type mismatch:  -> (pointing to):  transmorphic found where pointer expected type mismatch:  -> (pointing to):  transmorphic found where pointer expected expression invalid type mismatch:  -> (pointing to):  transmorphic found where pointer expected
                 <istmt>:  3499  varinfo not found type mismatch:  -> (pointing to):  transmorphic found where pointer expected
                 <istmt>:  3499  numrowscheck not found type mismatch:  -> (pointing to):  transmorphic found where pointer expected expression invalid 'return' found where almost anything else expected expression invalid class libjson undefined
                 <istmt>:  3499  numrows not found type mismatch:  -> (pointing to):  transmorphic found where pointer expected type mismatch:  -> (pointing to):  transmorphic found where pointer expected type mismatch:  -> (pointing to):  transmorphic found where pointer expected type mismatch:  -> (pointing to):  transmorphic found where pointer expected expression invalid 'return' found where almost anything else expected expression invalid class libjson undefined
                 <istmt>:  3499  numrows not found type mismatch:  -> (pointing to):  transmorphic found where pointer expected type mismatch:  -> (pointing to):  transmorphic found where pointer expected type mismatch:  -> (pointing to):  transmorphic found where pointer expected
                 <istmt>:  3499  tempvar not found
                 <istmt>:  3499  tokenstemp not found
                 <istmt>:  3499  startvar not found
                 <istmt>:  3499  r not found expression invalid 'return' found where almost anything else expected expression invalid type mismatch:  pointer = real not allowed type mismatch:  -> (pointing to):  transmorphic found where pointer expected type mismatch:  -> (pointing to):  transmorphic found where pointer expected type mismatch:  -> (pointing to):  transmorphic found where pointer expected type mismatch:  -> (pointing to):  transmorphic found where pointer expected
                 <istmt>:  3499  tval not found
                 <istmt>:  3499  tval not found expression invalid type mismatch:  -> (pointing to):  transmorphic found where pointer expected
                 <istmt>:  3499  tval not found expression invalid expression invalid
                 <istmt>:  3499  svarnames not found
                 <istmt>:  3499  V not found
                 <istmt>:  3499  rdata not found expression invalid type mismatch:  -> (pointing to):  transmorphic found where pointer expected 'return' found where almost anything else expected expression invalid 'else' found where almost anything else expected expression invalid class libjson undefined 'return' found where almost anything else expected expression invalid type mismatch:  -> (pointing to):  transmorphic found where pointer expected
                 <istmt>:  3499  tval not found
                 <istmt>:  3499  varinfo1 not found
                 <istmt>:  3499  liststrings not found
                 <istmt>:  3499  addstrings not found file temp_eddata_file_gen_012345.csv not found
                 stata():  3598  Stata returned error
                 <istmt>:     -  function returned error
                 <istmt>:  3499  varinfo1 not found
                 <istmt>:  3499  spops1 not found expression invalid 'else' found where almost anything else expected type mismatch:  -> (pointing to):  transmorphic found where pointer expected type mismatch:  -> (pointing to):  transmorphic found where pointer expected
                 <istmt>:  3499  tval not found
                 <istmt>:  3499  yearslist not found
                 <istmt>:  3499  tval not found
                 <istmt>:  3499  tbaseurl not found file temp_eddata_file_gen_012345.dta not found
                 stata():  3598  Stata returned error
                 <istmt>:     -  function returned error
expression invalid
no dataset in use
                 stata():  3598  Stata returned error
                 <istmt>:     -  function returned error
'return' found where almost anything else expected expression invalid type mismatch:  pointer = real not allowed type mismatch:  -> (pointing to):  transmorphic found where pointer expected type mismatch:  -> (pointing to):  transmorphic found where pointer expected type mismatch:  -> (pointing to):  transmorphic found where pointer expected
                 <istmt>:  3499  epcount1 not found
                 <istmt>:  3499  url2 not found
                 <istmt>:  3499  nextpage not found expression invalid checking libjson consistency and verifying not already installed...
installing into /Users/jdm_work/Library/Application Support/Stata/ado/plus/...
installation complete.
            getalldata():  3499  endpointstrings() not found
                 <istmt>:     -  function returned error
r(3499);

. 
. educationdata using "college ipeds directory", meta
            getalldata():  3499  endpointstrings() not found
                 <istmt>:     -  function returned error
r(3499);

**Comment by grahamimac** [comment]
Thanks Matt. I'll look into this shortly. This typically happens when the package installs `libjson` on it's first round, and the typical solution is the uninstall and reinstall. I think in future versions we may throw an error to force the user to install libjson manually, or find a way to better integrate the libjson install without these errors.

**Comment by grahamimac** [comment]
Current version and instructions now direct people to install libjson before installing the package, so I'm considering this closed.
