### ISSUE TITLE
CCD school directory missing all seasch for year=2014

### ISSUE THREAD

**Issue by barose1** [UrbanInstitute/education-data-package-stata#52]
The variable seasch is entirely missing for the CCD school directory for 2014 (2014-15). This may be due to the extensive changes NCES made to the CCD that year, including renaming the seasch variable to ST_SCHID. 

In Stata/SE 15.1 I used: 

educationdata using "school ccd directory", sub(fips=24) clear
by year, sort: tab seasch

There are seasch values for all years except 2014.

I also tried:

educationdata using "school ccd directory", sub(year=2014) clear
tab seasch

Stata reported "no observations".

**Comment by vrosenboom** [comment]
Thanks for point this out @barose1! We're looking into this issue now.

**Comment by vrosenboom** [comment]
@ericatheresa do you remember if this issue was resolved in your cleaning of CCD?

**Comment by grahamimac** [comment]
Tested and this seems to work now, so closing.

**Comment by barose1** [comment]
Confirmed, working now, thanks!
