### ISSUE TITLE
Java Error from Stata

### ISSUE THREAD

**Issue by wbuchanan** [UrbanInstitute/education-data-package-stata#54]
```Stata
. educationdata using "college ipeds directory", meta
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certi
> fication path to requested target
 Error -603, Unable to open URL: file could not be opened
            getresults():  3010  attempt to dereference NULL pointer
       endpointstrings():     -  function returned error
            getalldata():     -  function returned error
                 <istmt>:     -  function returned error
r(3010);
```

Stata/MP 15.1 for Mac (64-bit Intel)
Revision 15 Oct 2018

```Stata
. query java
------------------------------------------------------------------------------------------------------------------------------------------------------------
    Java system information
      Java initialized     yes
      heap usage           247m
      system classpath     /Applications/Stata/utilities/jar/libstata-core.jar:/Applications/Stata/utilities/jar/libdeps-core.jar:/Applications/Stata/utilit
> ies/jar/sfi-api.jar:
      javacall classpath   /Applications/Stata/ado/base/jar/libdeps-plugin.jar:/Applications/Stata/ado/base/jar/libstata-plugin.jar

    Advanced Java settings
      set java_heapmax     8192m
      set java_vmpath      /Applications/Stata/utilities/java/macosx-x64/jre1.8.0_162.jre/Contents/Home/lib/jli/libjli.dylib
```

Not sure what is going on with this error.  I'll try to use a different version of Java to see if that addresses it but at least wanted to make you aware of it.

**Comment by grahamimac** [comment]
Thanks Will. I can replicate this error, which has only popped up very recently, with no changes on our end. We are looking into it now and will get back to you when we have a solution.  This seems to only affect Stata, as all other programming implementations are working as usual. 

We apologize for the interruption in API service - we'll try to trace the error and get this back working as soon as we can. If you find anything in the meantime, please let us know.

**Comment by grahamimac** [comment]
R does not use Java. This is likely a certificate issue, however, as we experience the error in Python as well (which we can override, so it's not as big of an issue), which does not use the same method as Stata. We're looking into it and will let you know as soon as we have a solution. Thanks for your help!

**Comment by grahamimac** [comment]
@wbuchanan & @ChrisMarsicano, thank you again for reporting this issue. We found that it was an intermediate https certificate error on our end, which we have now resolved. I've tested and confirmed that the package should now work as expected.

We apologize for the interruption. Thanks for your patience. If you have further trouble with this or other issues, please don't hesitate to let us know.
