### ISSUE TITLE
r(3010) Error -603

### ISSUE THREAD

**Issue by ChrisMarsicano** [UrbanInstitute/education-data-package-stata#55]
Love this tool, not sure why it isn't working for me right now. 

Let me know what I need to do to fix this error message! Thanks!

. educationdata using "college ipeds directory", sub(year=2005) clear
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
 Error -603, Unable to open URL: file could not be opened
            getresults():  3010  attempt to dereference NULL pointer
       endpointstrings():     -  function returned error
            getalldata():     -  function returned error
                 <istmt>:     -  function returned error
r(3010);

**Comment by grahamimac** [comment]
Thanks for reporting Chris, we always appreciate feedback. We are aware of the error and are working on a solution. We apologize for the downtime.

This has already been reported here: https://github.com/UrbanInstitute/education-data-package-stata/issues/54. Please check that thread for updates and when we resolve it, we'll reply there.
