### ISSUE TITLE
Multiple years and/or grades

### ISSUE THREAD

**Issue by vrosenboom** [UrbanInstitute/education-data-package-stata#56]
I've had a few folks ask about downloading multiple years and grades in one line of code. I wasn't sure if there was talk about this functionality, but I thought I'd flag the issue. Right now I'm just recommending looping through the educationdata call for a given year and/or grade, saves it as a tempfile, and then later appends them all together.

**Comment by ericatheresa** [comment]
This should already be possible, for example: 
educationdata using "district ccd enrollment race sex", sub(year=2011:2015 grade=6:8) clear

**Comment by grahamimac** [comment]
Exactly. `help educationdata` should have examples of how to do this right at the top of the help page.

If people are finding this too slow, they can download the CSVs (examples also provided right at the top of the help page) using the `csv` option. E.g., you can modify Erica's query if they'd like:

`educationdata using "district ccd enrollment race sex", sub(year=2011:2015 grade=6:8) csv clear`

**Comment by grahamimac** [comment]
Closing this as resolved, but please let me know if I missed anything.
