### ISSUE TITLE
More helpful error message for incorrect variable

### ISSUE THREAD

**Issue by grahamimac** [UrbanInstitute/education-data-package-stata#58]
`. educationdata using "school edfacts assessments", sub(grade=99 year=2017 fips=11)`

Produces the following error:
Error: The name of the category ('school', 'district', or 'college') is correct, but the name of the 
> dataset you chose is not. Please verify the list of allowed options by typing "help educationdata".

But `educationdata using "school edfacts assessments", sub(grade_edfacts=99 year=2016 fips=11) clear staging` works. So `grade` vs `grade_edfacts` is the issue, not assessments. So the error message could be more helpful.

**Comment by ericatheresa** [comment]
@grahamimac I think there were three things going on here: one was grade_edfacts, one was year, and one was staging -- although the Stata package was updated, the new data are not on production yet so can't be accessed via the Stata package without the staging option yet.

**Comment by grahamimac** [comment]
Correct, I put this up here because I didn't have time to dig into it, but now that I have I agree. Thanks Erica! Closing.
