### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by danlfay** [UrbanInstitute/education-data-package-stata#93]
Hello, I'm trying to pull some data and getting some error messages.  

Here is the code:
educationdata using "school crdc retention disability sex", csv clear

and I get the following error: 

file temp_eddata_file_gen_012345.dta not found
                 stata():  3598  Stata returned error
           downloadcsv():     -  function returned error
            getalldata():     -  function returned error
                 <istmt>:     -  function returned error

**Comment by erika-tyagi** [comment]
Hi @danlfay - thanks for reporting this, and apologies for the delayed response. I just pushed an update that fixes this issue. Note that this downloads 9+ GB of data (you can see CSV file sizes from the documentation site [here](https://educationdata.urban.org/documentation/schools.html#crdc-retention-by-disability-and-sex)), so it will take some time (it took ~5 minutes for me just now). Let us know if you have any questions or run into additional issues. 

<img width="400" alt="Screenshot 2023-11-07 at 11 25 35 AM" src="https://github.com/UrbanInstitute/education-data-package-stata/assets/47676353/a9489d5f-37bf-4fcb-bd44-b13f99ba9176">
